In [1]:
distance = [10, 15, 17, 26]
time = [.30, .47, .55, 1.20]
speed = distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [3]:
# NumPy numerical python is the foundational package for mathematical computing in Python
# 1. Support fast and efficient multidimentsional arrays (ndarray)
# 2. Executes element-wise computations and mathematical calculations
# 3. Performs linear algebric operations, Fourier transforms, and random number generations
# 4. Tools for reading and writing array based datasets to disk
# 5. Efficient was of storing data and manipulating data
# 6. Tools for integration language code C, C++

# Primary container to exchange data between algorithms
import numpy as np

In [6]:
np_distance = np.array(distance)
np_time = np.array(time)
speed = np_distance/np_time
print(speed)

[33.33333333 31.91489362 30.90909091 21.66666667]


In [36]:
# nd array in Python is used as primary container to exchange data between algorithms
# 1d 1-axes, 2d 2-axes, 3d 3-axes
one = np.array([5,7,9])
print('1d 1-axis rank 1 3x1','\n', one)
print('ndim: ', one.ndim)
print('shape: ', one.shape)
print('size: ', one.size)
print('dtype: ', one.dtype) #int32
two = np.array([[0,1,2],[5,6,7]])
print('2d 2-axis rank 2 2x3','\n', two)
print('ndim: ', two.ndim)
print('shape: ', two.shape)
print('size: ', two.size)
print('dtype: ', two.dtype) #int32
three = np.array([[[0.56,1,2],[2,3,4],[4,5,6]], [[0,1,2],[2,3,4],[4,5,6]], [[0,1,2],[2,3,4],[4,5,6]]])
print('3d 3-axis rank 2 3x3x3', '\n', three)
print('ndim: ', three.ndim) # 1,2,3
print('shape: ', three.shape) # nxmxt
print('size: ', three.size) # number of elements
print('dtype', three.dtype) #float64

1d 1-axis rank 1 3x1 
 [5 7 9]
ndim:  1
shape:  (3,)
size:  3
dtype:  int32
2d 2-axis rank 2 2x3 
 [[0 1 2]
 [5 6 7]]
ndim:  2
shape:  (2, 3)
size:  6
dtype:  int32
3d 3-axis rank 2 3x3x3 
 [[[0.56 1.   2.  ]
  [2.   3.   4.  ]
  [4.   5.   6.  ]]

 [[0.   1.   2.  ]
  [2.   3.   4.  ]
  [4.   5.   6.  ]]

 [[0.   1.   2.  ]
  [2.   3.   4.  ]
  [4.   5.   6.  ]]]
ndim:  3
shape:  (3, 3, 3)
size:  27
dtype float64


In [9]:
# Create an array
numpy_array = np.array([1,2,3,4]) # mention array elements within parenthesis
print(numpy_array)

[1 2 3 4]


In [30]:
# Create an array with zeroes
# curve braces instead of square
numpy_array = np.zeros((3,3)) # mention shape of array within praentheses
print(numpy_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
# Create an array with ones
numpy_array = np.ones((3,3))
print(numpy_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# Create an array with empty
empty_array = np.empty((5,7))
empty_array
# fills with random numbers

array([[1.08543750e-311, 1.08545523e-311, 0.00000000e+000,
        0.00000000e+000, 3.81674046e-308, 1.16096346e-028,
        1.04857803e-142],
       [1.16467185e-028, 7.25941385e+271, 1.63672836e-152,
        2.69371829e+132, 4.10115911e+223, 1.16633589e+200,
        3.04519390e-067],
       [1.21691782e+132, 4.10114366e+223, 1.10157796e+141,
        5.86836989e-091, 5.04496173e+223, 1.02856463e+271,
        1.21995056e-153],
       [6.12743595e-154, 8.49052769e+136, 1.57563406e-153,
        1.81154498e-152, 8.63403817e+140, 1.96860020e-062,
        8.94279358e+130],
       [8.53718807e+136, 1.21995029e-153, 6.12743595e-154,
        8.49052769e+136, 1.57563406e-153, 5.88568417e+294,
        1.08543213e-311]])

In [17]:
# Create an array with arange method
# np.arange(10)
numpy_arange = np.arange(15)
print(numpy_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [18]:
# Reshape array
# arr.reshape(3, 5)
numpy_arange.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
# use linspace for linearly spaced data elements
# In the linspace function,
# 4 is the starting element and 13 is the end element.
# The last number 7 specifies that a total of seven equally spaced elements should be created
# between 4 and 13, both numbers inclusive. In this case,
# the linspace function creates the following array: [ 4., 5.5, 7., 8.5, 10., 11.5, 13. ]
np_linspace = np.linspace(1,5,10) # first element, last element, number of equidistant elements
np_linspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [51]:
# One Dimensional Array
oneD_array = np.arange(15)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
# Two Dimensional Array
twoD_array = oneD_array.reshape(3,5)
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
# Three Dimensional Array
threeD_array = np.arange(27).reshape(3,3,3)
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [75]:
# ndarray.ndim
# refers to the number of axes (dimensions) of the array
# It is also called as the rank of the array
np_teams = np.array(['KKR', 'MI', 'CSK', 'SRH', 'DC', 'KXIP'])
print(np_teams.ndim)
np_teams_captians = np.array([['KKR', 'MI', 'CSK', 'SRH', 'DC', 'KXIP'],['Dinesh', 'Rohit', 'Dhoni', 'David', 'Pant', 'Rahul']])
print(np_teams_captians.ndim)

1
2


In [76]:
# ndarry.shape
# This consists of a tuple of integer showing the size of the array in each dimensions
print(np_teams.shape)
print(np_teams_captians.shape)

(6,)
(2, 6)


In [80]:
# ndarray.size
print(np_teams.size)
print(np_teams_captians.size)

6
12


In [82]:
# ndarray.dtype
# an object that describes the type of the element in the array
np_teams

array(['KKR', 'MI', 'CSK', 'SRH', 'DC', 'KXIP'], dtype='<U4')

In [83]:
np_teams_captians

array([['KKR', 'MI', 'CSK', 'SRH', 'DC', 'KXIP'],
       ['Dinesh', 'Rohit', 'Dhoni', 'David', 'Pant', 'Rahul']],
      dtype='<U6')

In [84]:
np_teams_captians.dtype

dtype('<U6')

In [87]:
# Basic numpy operations
# 1. Vector Addition
dataset_one = [10,15,17,26]
dataset_two = [21,31,51,65]
np_dataset_one = np.array(dataset_one)
np_dataset_two = np.array(dataset_two)
np_total = np_dataset_one + np_dataset_two
print(np_total)

[31 46 68 91]


In [89]:
np.add(np_dataset_one, np_dataset_two)

array([31, 46, 68, 91])

In [91]:
np.subtract(np_dataset_one, np_dataset_two)

array([-11, -16, -34, -39])

In [103]:
# A man works for 20 days in a row at hourly rate of 10 dollars
# given the hours he worked calculate one week's total income
# 7 8 5 4 9 13 1 4 3 5 8 10 11 12 4 4 4 8 6 12
arr = np.array([7, 8, 5, 4, 9, 13, 1, 4, 3, 5, 8, 10, 11, 12, 4, 4, 4, 8, 6, 12])*10
print(arr)
sum(arr)

[ 70  80  50  40  90 130  10  40  30  50  80 100 110 120  40  40  40  80
  60 120]


1380

In [106]:
# given a bonus of 5 dollars for working more than 5 hours
# compare numpy data
days = arr[arr>50].size
print(sum(arr)+days*5)

1435


In [110]:
# penalty of 3 dollar for working less than 5 hours
# logical and
days = np.logical_and(arr>10,arr<50)
days

array([False, False, False,  True, False, False, False,  True,  True,
       False, False, False, False, False,  True,  True,  True, False,
       False, False])

In [112]:
# logical not
np.logical_not(arr>60)

array([False, False,  True,  True, False, False,  True,  True,  True,
        True, False, False, False, False,  True,  True,  True, False,
        True, False])

In [38]:
trials = np.array([[10,15,17,26],[22,23,24,25]])
print(trials)
print(trials.ndim)
print(trials.shape)
print(trials.size)
print(trials.dtype)

trial_one = trials[0]
print(trial_one)
print(trial_one.ndim)
print(trial_one.shape)
print(trial_one.size)
print(trial_one.dtype)

trial_two = trials[1]
print(trial_two)
print(trial_two.ndim)
print(trial_two.shape)
print(trial_two.size)
print(trial_two.dtype)

[[10 15 17 26]
 [22 23 24 25]]
2
(2, 4)
8
int32
[10 15 17 26]
1
(4,)
4
int32
[22 23 24 25]
1
(4,)
4
int32


In [41]:
trials[1][1]

23

In [45]:
trials[:,1] # if want to select both row from one column
# use colon and then specify column after ,

array([15, 23])

In [43]:
trials.shape #  2rows 4columns

(2, 4)

In [126]:
# get data of 3rd and 4th row
trials[:,2:] # last index in exclusive

array([[17, 26],
       [24, 25]])

In [128]:
# get data of 2nd and 3rd row
trials[:,1:3]

array([[15, 17],
       [23, 24]])

In [132]:
# iterate through data
for pos, data in enumerate(trials):
    print(pos, data)

0 [10 15 17 26]
1 [22 23 24 25]


In [135]:
# Indexing with boolean array
passed = trials>20
print(passed) # get boolean array
trials[passed] # get true values

[[False False False  True]
 [ True  True  True  True]]


array([26, 22, 23, 24, 25])