In [3]:
# inverse of matrix
import numpy as np
from scipy import linalg
matrix = np.array([[10,15],[2,7]])
print(matrix)
print(type(matrix))
linalg.inv(matrix)

[[10 15]
 [ 2  7]]
<class 'numpy.ndarray'>


array([[ 0.175, -0.375],
       [-0.05 ,  0.25 ]])

In [5]:
# determinant
import numpy as np
from scipy import linalg
matrix2 =  np.array([[10,15],[2,7]])
print(matrix2)
linalg.det(matrix2)

[[10 15]
 [ 2  7]]


40.0

In [6]:
# linear equations
import numpy as np
from scipy import linalg
# 2x + 3y + z = 21
# -x +5y + 4z = 9
# 3x + 2y + 9z = 6
numArray = np.array([[2,3,1],[-1,5,4],[3,2,9]])
numValue = np.array([21,9,6])
linalg.solve(numArray,numValue)

array([ 4.95,  4.35, -1.95])

In [9]:
num = np.array([2,3,1]) # hence the input needs to be a square matrix
val = np.array([21])
linalg.solve(num,val)

ValueError: Input a needs to be a square matrix.

In [10]:
# Single Value Decomposition
# method achieved by factorization of a matrix
import numpy as np
from scipy import linalg

numSvd = np.array([[3,5,1],[9,5,7]])
print(numSvd)
linalg.svd(numSvd)

# first array output is U (Unitary Matrix) holds values collected by columns 
# Sigma or square root of eigenvalues
# VH is values collected into unitary matrix

[[3 5 1]
 [9 5 7]]


(array([[-0.37879831,  0.92547925],
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))