In [2]:
import numpy as np

In [4]:
# Copy and Views
nyc = np.array([['Vinay'],['Pursnani']])
print(nyc)
nye = nyc
print(nye)
print(nye is nyc)

[['Vinay']
 ['Pursnani']]
[['Vinay']
 ['Pursnani']]
True


In [6]:
# View Shallow copy
view_nyc = nyc.view()
print(view_nyc)
print(nyc)# the original value also changes

[['Vinay']
 ['Pursnani']]
[['Vinay']
 ['Pursnani']]


In [7]:
print(nye) # also changes the assigned value

[['Vinay']
 ['Pursnani']]


In [8]:
# Copy
abc = np.array([['1','2','3']])
copy_abc = abc.copy()
copy_abc

array([['1', '2', '3']], dtype='<U1')

In [9]:
copy_abc='2'
print(abc)
print(copy_abc)
# does not change the original array

[['1' '2' '3']]
2


In [10]:
# numpy universal function
# avg, ceil, dot, floor, inner, inverse
np_sqrt = np.sqrt([2,3,4,5])
np_sqrt

array([1.41421356, 1.73205081, 2.        , 2.23606798])

In [11]:
from numpy import pi

In [12]:
print(np.cos(0))

1.0


In [13]:
print(np.sin(pi/2))

1.0


In [4]:
# Some Common methods for manipulating shapes
# Split, Flatten, Resize, Reshape, Stack
arr = np.array(([10,11,12,13,14],[13,15,16,23,19]))

In [5]:
arr.ravel()

array([10, 11, 12, 13, 14, 13, 15, 16, 23, 19])

In [6]:
arr.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [13, 15, 16, 23, 19]])

In [7]:
arr.resize(5,2)
arr

array([[10, 11],
       [12, 13],
       [14, 13],
       [15, 16],
       [23, 19]])

In [11]:
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[10],
       [12],
       [14],
       [15],
       [23]]), array([[11],
       [13],
       [13],
       [16],
       [19]])]


In [24]:
x = np.hstack((arr,arr))
print(x)

[[10 11 10 11]
 [12 13 12 13]
 [14 13 14 13]
 [15 16 15 16]
 [23 19 23 19]]


In [18]:
#Broadcasting
arrA = np.array([2,3,5,8])
arrB = np.array([.2,.2,.2,.2])
# arrA * arrB
# array([0.4, 0.6, 1. , 1.6])

In [20]:
scalar = .2
arrA * scalar

array([0.4, 0.6, 1. , 1.6])

In [22]:
incomeOne = np.array([165,132,110,119,123])
incomeTwo = np.array([155,145,120,110,165])
total = incomeOne + incomeTwo
print(total)
total/15 # Broadcasting

[320 277 230 229 288]


array([21.33333333, 18.46666667, 15.33333333, 15.26666667, 19.2       ])

In [25]:
# transpose helps you interchange rows and columns, vice-versa
x.transpose()

array([[10, 12, 14, 15, 23],
       [11, 13, 13, 16, 19],
       [10, 12, 14, 15, 23],
       [11, 13, 13, 16, 19]])

In [32]:
# inverse and trace function
sq_mat = np.empty(9)
# sq_mat.reshape(3,3)
sq_mats = np.linspace(1,4,4)
sq_mats = sq_mats.reshape(2,2)
# for i in range(9)
invrse = np.linalg.inv(sq_mats)
print(invrse)
print(sq_mats)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1. 2.]
 [3. 4.]]


In [35]:
print(np.trace(sq_mats))
print(np.trace(invrse))

5.0
-2.4999999999999996
